### ISSUE TITLE
Part 3: Time to cross stitch

### ISSUE THREAD

**Issue by sgibson91** [sgibson91/cross-stitch-carpentry#6]
### Content

- Now it’s time to cross stitch!
    - To make the first stitch, push your needle through from the underside of the fabric through what will be the top left corner of your stitch. Be careful not to pull all the thread through! Now push your needle through the hole 1 space to the right and 1 space down from where we came up. This will create the first diagonal \ part of the cross stitch. Now on the back of your fabric, pass the needle through the looped end of your thread and pull it taut. This should make an anchor preventing your thread from pulling through the fabric.
    - Loop start video: https://youtu.be/HLxIYeZJHeE
    - Make a cross stitch for each square with a colour/symbol on the pattern that corresponds to the thread your using. There is a legend on the pattern that connects the colours/symbols on the pattern to the numbers on the paper bands around the thread.
    - When cross stitching, there’s a couple of best practice tips that will help make your work look super neat. Ultimately you can stitch however works best for you, just bear these tips in mind when thinking about your workflow.
    - Always make sure your crosses go the same way. So if you make your crosses by going left-to-right (\) first, then right-to-left (/) on top, make sure all your crosses do this. It will give a uniformity to your stitching.
    - Do a row of half stitches then come back along the line to finish off the cross. It can save a lot of time and be a more efficient way to stitch if you work along a line with half stitches first (for example, \\\), then come back down the line to finish off the crosses (so, ///). This again helps neaten your work up but also means there’s less thread to unpick if you make a mistake.
    - A Beginner’s Guide to Cross Stitch Blog: https://redgatestitchery.com/blogs/red-gate-stitchery/a-step-by-step-guide-to-cross-stitch

**Comment by malvikasharan** [comment]
Looks great! You can merge.
